package de.upb.crypto.clarc.protocols.parameters;

import de.upb.crypto.craco.interfaces.PlainText;

/**
 * An announcement is the first message of a three way protocol. It is generated by the prover and send to the verifier.
 * Some protocols may use more than one announcement.
 */
public interface Announcement extends PlainText {
    String RECOVERY_METHOD = "recreateAnnouncement";

}
