package de.upb.crypto.clarc.protocols.parameters;

import de.upb.crypto.math.serialization.Representable;

/**
 * A challenge it the second message of a three way protocol. It is generated by the verifier and send to the prover.
 * Some protocols may use more than one challenge, but this is rather unlikely.
 */
public interface Challenge extends Representable {
    String RECOVERY_METHOD = "recreateChallenge";
}
