language: java
install: true
jdk:
- openjdk8
- openjdk11
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
stages:
- name: build
- name: snapshot
  if: branch = master
- name: release
  if: branch = release
jobs:
  include:
  - stage: build
    script: "./gradlew build"
  - stage: snapshot
    script: "./gradlew publish -x test -Dsnapshot=true -Dnexus.user=$NEXUS_USER -Dnexus.key=$NEXUS_KEY
      -Dbuild.number=$TRAVIS_BUILD_NUMBER"
  - stage: release
    script: "./gradlew publish -x test -Dnexus.user=$NEXUS_USER -Dnexus.key=$NEXUS_KEY
      -Dbuild.number=$TRAVIS_BUILD_NUMBER"
deploy:
  provider: releases
  api_key:
    secure: MoDrm3wDpaOF+6Q2zfHg2x7GUJPDATTiMFaMIaSXvJoAOA2QQmn7dHQFN89uvdYyfgyV3LGDLYjEExCVicEeWfrJsFScRekb1zS842TrDyvV88gtQ/e9iYWMcdiaEpw96EvRdhH3X1Naz1wPf7uZu3cVmnI/TSfsyAPFCUNT8znMR+s0o7KxgnXU/v1bEatEQv+PLHsVK/6l8qbGtfs7szYtejnxcx3drypT6Q/dxXKJU3jFJ2exMiu4P74PrtYZM9W57S8j3IPS9rjY681aR9vrtO39Gq8LqBu2r8VW8NHdjwBfcK2tJqOVqDoE8/w1qm5PDROuuix5OF4//Fm4JC3BtFhN22QSFmPCx36JWCnFRcsDXaIZgxVGB8VbO3l0DJV1aA5gMQfhaLAT1GC5RO5EGOletASjg6AgTkt3McdcQKu5DDsI7kDeJGSmxQNg/ETBqFkjHZwFi2L6XpUFICyTOq5b0keyOfVlUOi2Geni7WBGPtxh5/TU8yZMOAjUh3jSXCbIa/VotsvqRN7LHmtGG4GvOYZz0FG1QwpfQ8keeP+n8MycyC5AIufgDxDEPCkyVo9UCbNa29nxIXg24/swgD1hFIe6TyMGq9NSC5AcALXdq+l3gtOFGWYlPlJpdJ51jYhOyZnVzWG/EHvogMEfNUBnLnu2mv3MP4Ljn5s=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: upbcuk/upb.crypto.protocols
    branch: release