language: java
install: true
jdk:
- openjdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
stages:
- name: test
- name: build
- name: snapshot
  if: branch = master
- name: release
  if: branch = release
jobs:
  include:
  - stage: test
    script: "./gradlew test"
  - stage: build
    script: "./gradlew build -x test"
  - stage: snapshot
    script: "./gradlew publish -x test -Dsnapshot=true -Dnexus.user=$NEXUS_USER -Dnexus.key=$NEXUS_KEY
      -Dbuild.number=$TRAVIS_BUILD_NUMBER"
  - stage: release
    script: "./gradlew publish -x test -Dnexus.user=$NEXUS_USER -Dnexus.key=$NEXUS_KEY
      -Dbuild.number=$TRAVIS_BUILD_NUMBER"
deploy:
  provider: releases
  api_key:
    secure: fr/x2AYLD7F1j32ySxVk/RGUFw4zLECnAs6vOIoZpjiRnUiZ0vzl+U79VCa8tC+Y+foRGhmcGGLJGSzwK6DLxozsXuA7M2iZ6lUEUBKpL8RPKBX8Y3LHwDQV9j0O4vF/g2baJGureqiJyE7C1NLOW4LM3gWwReV/i/s9Kg4CqVH+X7G9EbRB1C8Dr08FGhfMe8SpMkALOwxtl9XDLnN/99fURMZw+Lc7lGPZjio13CVjlnzuWvYqVJYRkucaZqfO5VDXkJzdea4Nf3nsw5P0c7/vfzTjmBPb0qzsWvGoehnZAsQnsD/Rul0JylNFBWv60UGlJmAy7uu/dmTSPl11Eb7AExkjt79/jlupeA4GUtvvzm8Hyn97tHsTFRyxiPy3nE0/7dS3Ofi3LgqE2wlUzdUQ0bK1jsY0oHLFe3Jy/0TXpHALYlqdc4D55zmTR33NKi+kUVbsknG3aEMc1R7kRYL/n7ytJHu+jm2eZ7Brf3DjGMTJ8Ql0rLKz+czi/iRDpCwmBX/JUYhWUx0H2G4xjWiRCjJ4hw38semsTxosSF7bgpdhNmGQIxiQmtKs4gOWbWbDXdWIbdM/MtxTjty6F5twwrlu0QEFsDz+a6MgH+5kB/LfxXiHMGOdC/oUYaxKzghSk8zN2QRxKfEkf8d0xsfEeGanuizwrUBUHIZUcAo=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: upbcuk/upb.crypto.protocols
    branch: release
